# Edit this file to configure your Docker Compose setup
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - loki-data:/loki
      - ./loki.yml:/mnt/config/loki.yml # Edit this line to point to your config file
    command: -config.file=/mnt/config/loki.yml
    ports:
      - "3100:3100"
    networks:
      - conveyor-network

volumes:
  loki-data:

networks:
  conveyor-network:
    driver: bridge
