name: Release Conveyor

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Download Go modules
        run: go mod tidy

      - name: Build Conveyor
        run: |
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -ldflags "-X 'github.com/open-ug/conveyor/cmd/cli.Version=${{ github.event.release.tag_name }}'" -o build/conveyor-${{ github.event.release.tag_name }}-linux-${{ matrix.goarch }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            config/loki.yml
            config/compose.yml
            build/conveyor-${{ github.event.release.tag_name }}-linux-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
