name: Release Configuration Files

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      etcd:
        image: bitnami/etcd:latest
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
        options: >-
          --health-cmd "etcdctl endpoint health --endpoints=http://127.0.0.1:2379 || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

      loki:
        image: grafana/loki:latest
        ports:
          - 3100:3100
        options: >-
          --health-cmd "wget --quiet --tries=1 --spider http://127.0.0.1:3100/ready || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
        # Mounting a config file isn't trivial in GitHub Actions, so use default config
        # If your tests require a custom config, bake it into a custom image

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Start NATS service
        run: |
          docker run -d \
            --name nats-js \
            -p 4222:4222 \
            -v "/tmp/nats-jsdata":"/data/js" \
            --health-cmd "wget --quiet --tries=1 --spider http://127.0.0.1:8222 || exit 1" \
            --health-interval 5s \
            --health-timeout 5s \
            --health-retries 20 \
            nats:latest -js --store_dir /data/js

      - name: Download Go modules
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./... -v -coverprofile=cover.out -covermode=atomic

      - name: Build Conveyor
        run: go build -o build/conveyor

      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: cover.out

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            config/loki.yml
            config/compose.yml
            build/conveyor-${{ github.event.release.tag_name }}-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
