name: Go Test

on:
  pull_request:
    branches:
      - "**" # Run on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the PR code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Download Go modules
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: make test

      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: cover.out
